### ISSUE TITLE
Can't edit transition text on Foundry 10.291 - module 0.4.4

### ISSUE THREAD

**Issue by Mad7eo** [p4535992/foundryvtt-scene-transitions#6]
I can't add/edit transition text anymore, worked with the previous foundry version

![Immagine 2022-12-03 110055](https://user-images.githubusercontent.com/89466389/205435304-91767a9f-8ed9-485a-9af0-ee448ce34966.jpg)

```
Foundry VTT | Rendering TransitionForm
commons.js:1703 Error: The content option for the editor handlebars helper has been deprecated. Please pass the content in as the first option to the helper and ensure it has already been enriched by TextEditor.enrichHTML if necessary
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at Object.editor (foundry.js:7080:21)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:37:145)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:6948:10)
    at async TransitionForm._renderInner (foundry.js:5271:16)
    at async TransitionForm._renderInner (foundry.js:5833:18)
    at async TransitionForm._render (foundry.js:5114:19)
    at async TransitionForm._render (foundry.js:5822:5)

logCompatibilityWarning | @ | commons.js:1703
-- | -- | --
  | editor | @ | foundry.js:7080
  | c | @ | handlebars.min.js:27
  | eval | @ | VM582:37
  | c | @ | handlebars.min.js:27
  | d | @ | handlebars.min.js:27
  | e | @ | handlebars.min.js:28
  | renderTemplate | @ | foundry.js:6948
  | await in renderTemplate (async) |   |  
  | _renderInner | @ | foundry.js:5271
  | _renderInner | @ | foundry.js:5833
  | _render | @ | foundry.js:5114
  | await in _render (async) |   |  
  | _render | @ | foundry.js:5822
  | render | @ | foundry.js:5067
  | callback | @ | scene-transitions.js:148
  | #onClickItem | @ | foundry.js:56177
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2


```

**Comment by Meliath1742** [comment]
Same here. It stills shows my previous text, but I can't go back in and edit.

**Comment by KamiKazeJEDI** [comment]
> Same here. It stills shows my previous text, but I can't go back in and edit.

I cannot even see the box to update/modify text.

**Comment by bradleyquinn** [comment]
Same, unfortunately.  All the previous transition texts are there, but any newly created one doesn't have the box to add text like before.

**Comment by FrontBrandon14** [comment]
I was about to create a post about this too

**Comment by orcnog** [comment]
+1

**Comment by p4535992** [comment]
Try out 0.4.5

**Comment by Mad7eo** [comment]
> 

Thank you! 0.4.5 works!
